FROM python:3.8

LABEL maintainer = "ibram reda"
COPY /techtrends /app
WORKDIR /app

# install requirements
RUN pip install -r requirements.txt

# ensure that database is initialized
RUN python init_db.py
EXPOSE 3111

CMD [ "python", "app.py" ]